### ISSUE TITLE
Very strange merge.  Any rebases?

### ISSUE THREAD

**Issue by burdges** [du5t/puccinia#1]
Just did a pull and got a merge, but no obvious changes.  Did you rebase for some reason?

**Comment by burdges** [comment]
Ahh!  You removed the target directory with a rebase.  Yey `diff -r`.  :)

**Comment by du5t** [comment]
Whoops, sorry! Did it work out?

**Comment by burdges** [comment]
Yes, but folks must know to do `pull -f` or a fresh clone, or else they wind up with crazy merges.
